#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Running Prettier check..."
npm run format:check || exit 1

echo "Running ESLint..."
npm run lint || exit 1

echo "Running tests..."
npm run test:ci || exit 1